"""한국 오피넷 유가 API의 비공식 Python 클라이언트."""

from .client import AsyncOpinetClient, OpinetClient
from .catalog import (
    API_CATALOG,
    SERVICE_KEY_URL,
    ApiCatalogItem,
    ApiParameter,
    get_api_catalog,
    get_api_catalog_item,
    get_api_catalog_options,
)
from .codes import (
    BrandCode,
    CanonicalFuelType,
    FuelType,
    ProductCode,
    SortOrder,
    StationType,
    bjd_sido_to_opinet,
    fuel_type_to_product_code,
    is_alddle,
    opinet_sido_to_bjd,
    product_code_to_fuel_type,
)
from .config import OpinetConfig
from .debug import (
    DebugRun,
    OpinetDebugClient,
    assert_case,
    build_fixture,
    jsonable,
    parse_debug_response,
    process_debug_result,
    redact_sensitive,
    remove_fields,
    replay_fixture_case,
    save_debug_fixture,
    save_fixture,
    slugify_case_name,
)
from .transport import AsyncHttpxTransport, SyncHttpxTransport, SyncTransport, Transport
from .exceptions import (
    OpinetAuthError,
    OpinetError,
    OpinetInvalidParameterError,
    OpinetNetworkError,
    OpinetNoDataError,
    OpinetRateLimitError,
    OpinetServerError,
)
from .models import AreaCode, AvgPrice, OilPrice, Station, StationDetail
from .normalized import (
    NormalizedFuelAverage,
    NormalizedFuelRegionCode,
    NormalizedFuelStation,
    NormalizedFuelStationDetail,
    NormalizedFuelStationDetailPrice,
    raw_to_json_safe,
    to_json_safe_raw,
)

__all__ = [
    "AreaCode",
    "API_CATALOG",
    "ApiCatalogItem",
    "ApiParameter",
    "AvgPrice",
    "AsyncOpinetClient",
    "BrandCode",
    "CanonicalFuelType",
    "DebugRun",
    "FuelType",
    "NormalizedFuelAverage",
    "NormalizedFuelRegionCode",
    "NormalizedFuelStation",
    "NormalizedFuelStationDetail",
    "NormalizedFuelStationDetailPrice",
    "OilPrice",
    "OpinetAuthError",
    "OpinetClient",
    "OpinetConfig",
    "OpinetDebugClient",
    "OpinetError",
    "OpinetInvalidParameterError",
    "OpinetNetworkError",
    "OpinetNoDataError",
    "OpinetRateLimitError",
    "OpinetServerError",
    "ProductCode",
    "SERVICE_KEY_URL",
    "SortOrder",
    "Station",
    "StationDetail",
    "StationType",
    "AsyncHttpxTransport",
    "SyncHttpxTransport",
    "SyncTransport",
    "Transport",
    "assert_case",
    "bjd_sido_to_opinet",
    "build_fixture",
    "fuel_type_to_product_code",
    "get_api_catalog",
    "get_api_catalog_item",
    "get_api_catalog_options",
    "is_alddle",
    "jsonable",
    "opinet_sido_to_bjd",
    "parse_debug_response",
    "process_debug_result",
    "product_code_to_fuel_type",
    "raw_to_json_safe",
    "redact_sensitive",
    "remove_fields",
    "replay_fixture_case",
    "save_debug_fixture",
    "save_fixture",
    "slugify_case_name",
    "to_json_safe_raw",
]
